# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Columbia Springs Labradoodles 
email: webmaster@cslabradoodles.com
description: > # this means to ignore newlines until "baseurl:"
  Columbia Springs Labradoodles - Australian Labradoodle Puppies in Brush Prairie,
  Washington. Our specialty is breeding sturdy, medium sized Australian Labradoodles
  with wavy fleece coats that are non-shedding, hypoallergenic and asthma friendly.
  Our dogs are friendly and playful yet highly intelligent and easy to train. 
  They love their people and become devoted companions as pets, therapy or service
  animals. Our dogs have proven especially patient and loving with children and live
  in harmony with other pets. Our doodles are definitely family friendly dogs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.spec.ml" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: cslabradoodles 
github_username:  cslabradoodles

# Build settings
markdown:
  kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# Other settings
timezone: UTC 
